[web]
web1 ansible_host=192.168.1.204 http_port=80 https_port=443
web2 ansible_host=192.168.1.205 http_port=8080 https_port=444

[db]
db1 ansible_host=192.168.1.206

[all:vars]
ansible_user=cristian
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
